base:
  project_name: mlflow-testing
  target: quality

load_dataset:
  drive_link: https://drive.google.com/file/d/1FCVWcNyBX6tFYjfORhnAvIwS8I8zV92j/view?usp=sharing
  raw_data: /data/raw
  file_name: wineq

make_dataset:
  test_split: 0.25
  seed: 41
  processed_data: /data/processed
  res_seed: 42

build_features:
  extended_data: /data/extended

train_model:
  n_estimators: 100
  criterion: gini
  seed: 43
  max_depth: 80
  model_dir: /models

model_tunning:
  split: 0.25
  seed: 42

mlflow_config:
  # artifacts_dir: artifacts
  trainingExpName: trainingExperiments
  tunningExpName: tunningExperiments
  remote_server_uri: http://localhost:5000     # 127.0.0.1
